# Generated by Django 6.0.7 on 2026-09-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], max_length=20),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
